export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: 'user/SET_CURRENT_USER',
  CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
  GOOGLE_SIGN_IN_START: 'user/GOOGLE_SIGN_IN_START',
  EMAIL_SIGN_IN_START: 'user/EMAIL_SIGN_IN_START',
  SIGN_IN_SUCCESS: 'user/SIGN_IN_SUCCESS',
  SIGN_IN_FAILED: 'user/SIGN_IN_FAILURE',
  SIGN_UP_START: 'user/SIGH_UP_START',
  SIGN_UP_SSUCCESS: 'user/SIGH_UP_SSUCCESS',
  SIGN_UP_FAILED: 'user/SIGH_UP_FAILED',
  SIGN_OUT_START: 'user/SIGH_OUT_START',
  SIGN_OUT_SSUCCESS: 'user/SIGH_OUT_SSUCCESS',
  SIGN_OUT_FAILD: 'user/SIGH_OUT_FAILD',
}